### ISSUE TITLE
Some ToTV records for OTC instruments in EoD files between 15-Oct-17 and 31-Dec-17 might not have DSB-ISIN component

### ISSUE THREAD

**Issue by NataliaKozlovich** [ANNA-DSB/ToTV-uToTV#18]
Some ToTV records in EoD files between 15-Oct-17 and 31-Dec-17, DSB-ISIN component might be missing for DSB-issued ISINs in cases when the ISIN was created/last updated prior T-1.

**Workaround:**
Please use the ISIN reference data from the DSB end of day data instead.

**Comment by AnnaDSBTechnicalSupport** [comment]
Deployed and validated in Production environment
