### ISSUE TITLE
Filtering out of Transparency periods in EoD ToTV files created in historical mode

### ISSUE THREAD

**Issue by NataliaKozlovich** [ANNA-DSB/ToTV-uToTV#20]
If DSB was to generate EoD ToTV files in the historical mode as opposed the normal daily mode, there could be a potential issue with the filtering out of no longer current reporting periods as the current process would use the Today’s date rather than the date of the ToTV file being created. Essentially transparency periods that are no longer current today could be filtered out, even if they were still current historically.  

**Workaround:** None needed. The most up-to-date transparency information will be made available in historical files as well as in the latest.

**Comment by NataliaKozlovich** [comment]
Released in UAT on 26 February 2020

**Comment by AnnaDSBTechnicalSupport** [comment]
Released in Production on 10 May 2020

**Comment by AnnaDSBTechnicalSupport** [comment]
Released in PRODUCTION on 10 May 2020
