### ISSUE TITLE
In a specific scenario when a DSB-issued ISIN that has a non-EZ underlying isin and the underlying has not been reported by a trading venue to FIRDS at the time of creation, some of such Instrument ISINs might remain uToTV=False in ToTV File Download after the underying gets reported to FIRDS by a trading venue

### ISSUE THREAD

**Issue by NataliaKozlovich** [ANNA-DSB/ToTV-uToTV#27]
In the following scenario only:
•	DSB ISIN is created with a non-EZ underlying
•	The underlying has not been reported to FIRDS by a venue at the time of creation (hence uToTV=False)
•	The underlying gets reported to FIRDS by a venue at a later date
•	The Instrument ISIN does not get reported to FIRDS/Transparency and is not updated by DSB (a possible reason for an update will be ISIN expiration)

After Underlying ISIN is reported by a TV to FIRDS, ToTV record for the Instrument ISIN enquired by API’s/GUI will show uToTV=True, whereas the File Download for the Instrument ISIN will continue to hold uToTV=False until there is a change to Instrument ISIN itself and its updated ToTV record is included in ToTV File Download. 

This affects ToTV File Download only and does not affect ToTV request by ISIN via API’s/GUI

**Comment by AnnaDSBTechnicalSupport** [comment]
Deployed in the UAT environment

**Comment by AnnaDSBTechnicalSupport** [comment]
Deployed in the Production environment
