### ISSUE TITLE
Updates to the DSB’s ToTV/uToTV transparency service

### ISSUE THREAD

**Issue by NataliaKozlovich** [ANNA-DSB/ToTV-uToTV#28]
The DSB will be amending its ToTV/uToTV codebase to address any changes in ESMA publication schedule of transparency calculations. In the event of delayed publication, the MiFID II reporting period that was last available for an instrument will remain on the DSB ToTV record until a new reporting period is available and the published record becomes valid. 

ESMA’s statement on the [Use of UK data in ESMA databases and performance of   MiFID II calculations in case of a no-deal Brexit](https://www.esma.europa.eu/document/use-uk-data-in-esma-databases-in-case-no-deal-brexit), published on 5 February 2019, set out the following   changes to the publication schedule of transparency calculations for   non-equity instruments:       

- Quarterly liquidity determination for bonds – 1st Jan 2019 – 31st Mar 2019 data might not be published on 1st May 2019     
- Annual transparency calculations for all non-equity instruments other than bonds (liquidity status, LIS, SSTI) – 1st Jan 2018 – 31st Dec 2018 data might not be published on 30th Apr 2019

The DSB is amending its underlying functionality such that any publication delays of MiFID II transparency data will result in data for the most recently published reporting period remaining available on the DSB ToTV record until a new reporting period becomes valid.

**Comment by AnnaDSBTechnicalSupport** [comment]
Fix deployed in UAT environment.

**Comment by NataliaKozlovich** [comment]
Deployed in Production on 11 May 2019
