### ISSUE TITLE
If ToTV File Download generation does not complete on the same day resulting in T data published on T+1, T+1 ToTV File Download data might not be made available.

### ISSUE THREAD

**Issue by AnnaDSBTechnicalSupport** [ANNA-DSB/ToTV-uToTV#29]
Problem:
If for any reason (e.g. due to a large number of files published by ESMA/FCA), the process of  ToTV File Download generation does not complete within the same date and T data published on T+1, the system does not generate T+1 ToTV File Download on T+1, and any data for T+1 are then included in T+2 ToTV File Download. 

Impact: 
UAT ToTV File Download is not available for June 3, 2019. Data for June 3 has been published in June 4, 2019 ToTV File Download in UAT. There is no impact on enquiring ToTV records via an API/GUI as it always returns the latest ToTV record containing all information published by ESMA/FCA.

Workaround: 
Any data not made available in ToTV File Download on T (due late ESMA/FCA publication or large number of files made available on the day), are made available in T+1 ToTV File Download as part of normal process.

**Comment by NataliaKozlovich** [comment]
Deployed in Production on 14 August 2019.
