### ISSUE TITLE
Introduction of idle timeout for ToTV requests

### ISSUE THREAD

**Issue by AnnaDSBTechnicalSupport** [ANNA-DSB/ToTV-uToTV#32]
Problem:
FIX API users sending ToTV FIX messages which coincides with the daily ToTV file generation processing time (09:00 am UTC to 12:00 pm UTC) may experience a delay in receiving responses as the database is busy during the generation of the files and there is a threshold limitation that may be exceeded that will result in throttling of requests.

Impact:
If you are utilizing the same FIX session for both ToTV and DSB ISIN requests and sending requests during the ToTV file generation processing time, responses may be delayed until the ToTV file generation has finished processing for the day. The DSB is putting in place a timeout for ToTV requests. Once the request’s idle timeout is reached a response will be sent back to the FIX API user.  Please note that there is no impact if you are using a separate FIX session for ToTV requests and DSB ISIN requests.

Workaround:
The DSB recommends FIX users to avoid sending ToTV requests during the ToTV file generation processing time (09:00 am UTC to 12:00 pm UTC) which will minimize delays in ToTV responses.
If possible, DSB also recommends that DSB ISIN requests are sent on different FIX sessions to ToTV requests.

**Comment by NataliaKozlovich** [comment]
Released in UAT on 26 February 2020.

**Comment by AnnaDSBTechnicalSupport** [comment]
Released in PRODUCTION on 10 May 2020.
